# @package _global_

model_type: xgb

tuning_ranges:
  n_estimators: [10, 200]
  max_depth: [2, 8]
  learning_rate: [0.0001, 0.05]
  subsample: [0.55, 1.0]  # fraction of features to subsample per depth step  
  colsample_bytree: [0.55, 1.0] # fraction of columns to subsample per tree
  #lambda: [0.0, 1.0]  #l2 reg term
  #alpha: [0.0, 1.0]  # l1 reg term
  gamma: [0.0, 5.0]  # alias: min_split_loss - larger = more conservative
