defaults:
  - _self_
  - model_type: xgb # choices=['torch', 'rf', 'xgb', 'svc', 'mlp', 'log']


df: yeo_Y/z/median/uni_clip_0.9999/multi_clip_N  # path to the preprocessed data folder from `data` parent folder.'
    #'If set to \'mock\', the UCI ML Breast Cancer dataset will be used.')
split: train/val  # choices=['train/test', 'train/val', 'dev/test', 'dev/val', 'no-split']
nf: 0  # k-fold k

#from_config:  # path to args config to load
v: 1  # verbosity
save: 0

#dt: 'data' # ['data', 'static', 'blood']
features:    # path to pkl file with pre-selected features

use_class_weights: 0
pos_weight: 0

miss_feats: 0  # whether to use missingness feats

blood: 0
imaging: 0
imaging_pca: 0
imaging_pca_var: 0  # choices=[0.8, 0.99]
clinical: 0
static: 1
sparse_img: 0

quantile_val: 0.99
fill_mode: 'median'
use_yeo_johnson: True