defaults:
  - _self_
  - tune_model: ???  #choices=['torch', 'rf', 'xgb', 'svc', 'mlp', 'log'])

df:  # 'path to the preprocessed data folder from `data` parent folder.'If set to \'mock\', the UCI ML Breast Cancer dataset will be used.'
features:  # path to pkl file of pre-selected features
nt: 10000
nf_inner: 3  # number of inner k-folds
load_path:  # name of study to continue training
eval_path:  # name of study to eval
pruner: median  # asha, median
pp: 0  # parallel processes
metric: prauc  # prauc, rocauc, acc
dts: imaging_blood_clinical  # Which features to use for optimization. Separated by comma, in any order can be:'
                             # blood, imaging, imaging_pca and clinical.'
                              # Can also be: "opt", then this selection will be tuned for.
imaging_pca_var: 0.8  # Explained variance used for PCA
freeze_prepro: 0  # Set to 1 to use frozen params for preprocessing

save_tune: 1

quantile_val: 0.99
fill_mode: 'median'
use_yeo_johnson: True

tuning_ranges:
  # general training
  use_class_weights: [0, 1]
  pos_weight: [0.1, 10.0]
  # preprocessing steps
  yeo: [0, 1]
  fill: ['median', 'iterative', 'minus']
  norm: ['z', 'minmax']
  remove_outliers: [0.95, 0.999, 0.9999]
  remove_multi_outliers: [0, 1]
  miss_feats: 0 #[0, 1]
