# @package _global_

m: mlp

model_args:
  hidden_layer_sizes: '(100,)'
  activation: relu  # ['logistic', 'tanh', 'relu']
  solver: sgd  # [sgd, adam]
  learning_rate: constant # 'constant', 'invscaling', 'adaptive'
  learning_rate_init: 0.001
  max_iter: 200
  tol: 1e-4
